# Generated by Django 4.2.4 on 2023-09-10 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('murabbiylar', '0002_alter_trenermodel_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='GymModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('location', models.URLField(blank=True, null=True)),
                ('open_time', models.DateField()),
                ('gym_logo', models.ImageField(blank=True, null=True, upload_to='media/')),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='murabbiylar.trenermodel')),
            ],
        ),
    ]
